### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by lfjd05** [HuangzhenL/Spider_anjuke#1]
首先谢谢作者提供的脚本。我运行了一段时间报了上面这个错误，查了下发现是爬取速度太快，安居客封了我的IP，这个脚本爬的城市比较多。所以在循环里面建议加time.sleep()不然容易被侦测到。

**Comment by HuangzhenL** [comment]
是会报错的，尝试time.sleep()也有可能会被检测到，最好的方式是用代理
